version: "3"
services:
  rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    restart: unless-stopped
    volumes:
      - ../.config/profiles:/profiles/en
      - /etc/localtime:/etc/localtime:ro
      - ../src/:/privacyVoiceAssistant/src/
      - ../lib/:/privacyVoiceAssistant/lib/
      - ../src/handlers/:/tmp/handler/
      - ./scripts/:/privacyVoiceAssistant/scripts/
      - type: bind
        source: ../.config/asound.conf
        target: /etc/asound.conf
      - type: bind
        source: ../.config/dbus-org.bluez.service
        target: /etc/systemd/system/dbus-org.bluez.service
      - type: bind
        source: ../.config/override.conf
        target: /etc/systemd/system/bluetooth.service.d/override.conf
    ports:
      - 12101:12101
    devices:
      - /dev/snd:/dev/snd
      # - /dev/hci0:/dev/hci0
    network_mode: host
    cap_add:
      - NET_ADMIN
    command: --user-profiles /profiles --profile en