version: "3"
services:
  rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    restart: unless-stopped
    volumes:
      - ../.config/profiles:/profiles/en
      - /etc/localtime:/etc/localtime:ro
      - ../src/:/privacyVoiceAssistant/src/
      - ../lib/:/privacyVoiceAssistant/lib/
      - ./scripts/:/privacyVoiceAssistant/scripts/
      - ../resources/:/privacyVoiceAssistant/resources/
      - type: bind
        source: ../.config/asound.conf
        target: /etc/asound.conf
      - type: bind
        source: ../requirements.txt
        target: /privacyVoiceAssistant/requirements.txt
    ports:
      - 12101:12101
    devices:
      - /dev/snd:/dev/snd
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    command: --user-profiles /profiles --profile en